add_definitions(-DPLATFORM_IOS)
#set(CMAKE_XCODE_SCHEME_ENABLE_GPU_API_VALIDATION TRUE)
#set(CMAKE_XCODE_SCHEME_ENABLE_GPU_FRAME_CAPTURE_MODE DISABLED)

set_target_properties(${PROJECT_NAME} PROPERTIES
        XCODE_ATTRIBUTE_LD_RUNPATH_SEARCH_PATHS "@executable_path/Frameworks"
        XCODE_EMBED_FRAMEWORKS "HyperRender;HyperGpu;${Vulkan_MoltenVK_LIBRARY};${Vulkan_Layer_VALIDATION};${Vulkan_LIBRARIES};"
        XCODE_EMBED_FRAMEWORKS_CODE_SIGN_ON_COPY "YES"
        MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION}
        MACOSX_BUNDLE_SHORT_VERSION_STRING ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}
        MACOSX_BUNDLE TRUE
        WIN32_EXECUTABLE TRUE
)

set_source_files_properties($ENV{VULKAN_SDK}/../iOS/share/vulkan PROPERTIES MACOSX_PACKAGE_LOCATION Resources)

target_link_libraries(${PROJECT_NAME} PRIVATE Qt6::Core Qt6::Gui Qt6::Widgets HyperRender)
